### ISSUE TITLE
3.0.0 has what appears to be some changes that make upgrading quite expensive.

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/node-fixturify-project#45]
1. default export is lost
require('fixturify-project'); no longer returns a project object, rather just the module context

2. DSL callback for contructor & helper methods are lost

Debugging.

```js
const  app = new Project('app', '3.1.1', app => {
        rsvp = app.addDependency('rsvp', '3.2.2', rsvp => {
          a = rsvp.addDependency('a', '1.1.1');
        });
        orange = app.addDependency('orange', '1.0.0');
        apple = app.addDependency('apple', '1.0.0');
      });
      app.writeSync(); 
 ```

doesn't seem to result in a directory structure containing the deps.

**Comment by stefanpenner** [comment]
working on a fix: https://github.com/stefanpenner/node-fixturify-project/pull/46

**Comment by stefanpenner** [comment]
1 & 2 are fixed

**Comment by stefanpenner** [comment]
```
 2) resolvePackagePath
       ._findPackagePath
         finds linked package.json:
     Error: this project has no baseDir yet. Either set one manually or call writeSync to have one chosen for you
      at Project.get baseDir [as baseDir] (node_modules/fixturify-project/index.js:164:19)
      at Context.<anonymous> (tests/resolve-package-path-test.ts:56:16)
      at processImmediate (internal/timers.js:461:21)
```

There appears to be an issue with nested deps not always having a baseDir, even if their parent has been written too

**Comment by stefanpenner** [comment]
I believe the most serious upgrade costs have been resolved. I may circle back and do more as i run into them.
