### ISSUE TITLE
Support scoped dependencies.

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/node-fixturify-project#6]
```
const FixturifyProject = require('fixturify-project');
let fixturifyProject = new FixturifyProject('awesome-proj', '0.0.0');
fixturifyProject.addDependency('@ember/test-helpers', '1.0.0');
```

triggers the following error:

```
    Error: Directory entry must not contain "/" or "\"
      at writeSync (node_modules/fixturify/index.js:68:15)
      at writeSync (node_modules/fixturify/index.js:102:11)
      at Object.writeSync (node_modules/fixturify/index.js:102:11)
```

**Comment by stefanpenner** [comment]
good call, fixing now.
